<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.bremersee</groupId>
    <artifactId>common-service-parent</artifactId>
    <version>3.1.2</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <artifactId>groupman</artifactId>
  <version>3.0.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>groupman</name>
  <description>A group management service</description>
  <url>https://github.com/bremersee/groupman</url>

  <properties>
    <github.repo>groupman</github.repo>
    <gh-pages-staging-dir>${project.build.directory}/staging</gh-pages-staging-dir>

    <start-class>org.bremersee.groupman.Application</start-class>

    <groupman-api-spring-reactive.version>3.0.0</groupman-api-spring-reactive.version>
    <lib-bundle.version>0.1.1</lib-bundle.version>
  </properties>

  <scm>
    <connection>scm:git:ssh://git@github.com:bremersee/groupman.git</connection>
    <developerConnection>
      scm:git:ssh://git@github.com:bremersee/groupman.git
    </developerConnection>
    <url>https://github.com/bremersee/groupman</url>
  </scm>

  <issueManagement>
    <url>https://github.com/bremersee/groupman/issues</url>
    <system>GitHub Issues</system>
  </issueManagement>

  <distributionManagement>
    <repository>
      <id>bremersee-releases</id>
      <url>https://nexus.bremersee.org/repository/maven-releases</url>
    </repository>
    <snapshotRepository>
      <id>bremersee-snapshots</id>
      <url>https://nexus.bremersee.org/repository/maven-snapshots</url>
    </snapshotRepository>
    <site>
      <id>bremersee-sites</id>
      <url>
        dav:https://nexus.bremersee.org/repository/maven-sites/groupman/${project.version}
      </url>
    </site>
  </distributionManagement>

  <!--
  <repositories>
    <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>https://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
  </repositories>
  -->

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.bremersee</groupId>
        <artifactId>lib-bundle</artifactId>
        <version>${lib-bundle.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>groupman-api-spring-reactive</artifactId>
      <version>${groupman-api-spring-reactive.version}</version>
    </dependency>
    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>common-exception-spring-boot-webflux-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>spring-integration-boot-autoconfigure</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>spring-integration-webflux</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>spring-integration-ldaptive</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-jose</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-resource-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>spring-integration-security-ldaptive</artifactId>
    </dependency>

    <dependency>
      <groupId>org.bremersee</groupId>
      <artifactId>comparator</artifactId>
    </dependency>

    <!-- MongoDB -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
      <version>4.11.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- Config client -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.retry</groupId>
      <artifactId>spring-retry</artifactId>
    </dependency>

    <!-- Eureka client -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <!-- Caffeine-backed LoadBalancer Cache -->
    <!--
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
    </dependency>
    -->

    <!-- Jwt cache -->
    <!--
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.codemonstur</groupId>
      <artifactId>embedded-redis</artifactId>
    </dependency>
    -->

    <!-- OpenAPI -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-ldap</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.unboundid</groupId>
      <artifactId>unboundid-ldapsdk</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>