bremersee:
  exception-mapping:
    api-paths:
      - /api/**
    default-exception-mapping-config:
      include-handler: true
      include-stack-trace: true
      include-cause: true
    exception-mappings:
      - exception-class-name: org.springframework.dao.DuplicateKeyException
        status: 409
        message: "Group already exists."
        code: "GRP:1000"
      - exception-class-name: org.springframework.dao.OptimisticLockingFailureException
        status: 409
        message: "Version is not up to date."
        code: "GRP:1001"
      - exception-class-name: java.lang.UnsupportedOperationException
        status: 400
        code: "GRP:1002"
  groupman:
    local-role: "ROLE_LOCAL_USER"

eureka:
  client:
    enabled: false

spring:
  profiles:
    active: in-memory
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/test}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized
  # Redis health check is broken: https://github.com/spring-projects/spring-boot/issues/22061 (will be fixed in 2.4.0)
  #health:
  #  redis:
  #    enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    ROOT: info
    com.netflix.eureka.registry: warn
    com.netflix.discovery.shared.resolver: warn
    org.springframework.cloud.configclient: warn

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.3.2

---

spring:
  config:
    activate:
      on-profile: jwt
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.bremersee.org/realms/eixe/protocol/openid-connect/certs
bremersee:
  authentication:
    jwt-converter:
      name-json-path: $.preferred_username
      first-name-json-path: $.given_name
      last-name-json-path: $.family_name
      roles-json-path: $.realm_access.roles
      roles-value-list: true
      role-prefix: "ROLE_"
      role-case-transformation: to_upper_case
      role-string-replacements:
        - regex: "[- ]"
          replacement: "_"
        - regex: "_ADMINS"
          replacement: "_ADMIN"

---

spring:
  config:
    activate:
      on-profile: in-memory

  security:
    user:
      name: testuser
      password: changeit
      roles:
        - "USER"
        - "LOCAL_USER"
        - "ADMIN"
        - "ACTUATOR_ADMIN"

---

spring:
  config:
    activate:
      on-profile: ldap

bremersee:
  ldaptive:
    ldap-url: ${LDAP_URL:ldaps://dc1.eixe.bremersee.org:636}
    use-start-tls: ${LDAP_START_TLS:false}
    bind-dn: ${LDAP_BIND_DN:}
    bind-credentials: ${LDAP_BIND_PASSWORD:}
    connection-validator:
      search-request:
        base-dn: ${LDAP_USER_DN:${bremersee.domain-controller.user-base-dn}}
    pooled: true
    connection-pool:
      validator:
        search-request:
          base-dn: ${LDAP_USER_DN:${bremersee.domain-controller.user-base-dn}}
  authentication:
    ldaptive:
      template: active_directory
      user-base-dn: ${LDAP_USER_DN:${bremersee.domain-controller.user-base-dn}}
      role-prefix: "ROLE_"
      role-case-transformation: to_upper_case
      role-string-replacements:
        - regex: "[- ]"
          replacement: "_"
        - regex: "_ADMINS"
          replacement: "_ADMIN"
      default-roles:
        - "ROLE_LOCAL_USER"
  domain-controller:
    group-base-dn: ${LDAP_GROUP_DN:cn=Users,dc=eixe,dc=bremersee,dc=org}
    user-base-dn: ${LDAP_USER_DN:cn=Users,dc=eixe,dc=bremersee,dc=org}
    admin-name: 'Administrator'
    ignored-ldap-groups:
      - 'Allowed RODC Password Replication Group'
      - 'Cert Publishers'
      - 'Denied RODC Password Replication Group'
      - 'DnsAdmins'
      - 'DnsUpdateProxy'
      - 'Domain Admins'
      - 'Domain Computers'
      - 'Domain Guests'
      - 'Domain Users'
      - 'Enterprise Admins'
      - 'Enterprise Read-only Domain Controllers'
      - 'Group Policy Creator Owners'
      - 'RAS and IAS Servers'
      - 'Read-only Domain Controllers'
