spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${bremersee.keycloak.base-uri}/realms/${bremersee.keycloak.realm}/protocol/openid-connect/certs
      client:
        provider:
          swagger-ui:
            authorization-uri: ${bremersee.keycloak.base-uri}/realms/${bremersee.keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${bremersee.keycloak.base-uri}/realms/${bremersee.keycloak.realm}/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: when_authorized

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    ROOT: info
    com.netflix.eureka.registry: warn
    com.netflix.discovery.shared.resolver: warn
    org.springframework.cloud.configclient: warn

bremersee:
  exception-mapping:
    api-paths:
      - /api/**
    default-exception-mapping-config:
      include-handler: true
      include-stack-trace: true
      include-cause: true
  web:
    cors:
      enabled: true
      # a45ab2d3-cbfe-4d4f-946c-aa696ae9632d
  keycloak:
    base-uri: https://openid.bremersee.org
    realm: eixe
    admin-client:
      enabled: false
      login-realm: master
      client-id: admin-cli
      username: admin
      password: change-it
  authentication:
    jwt-converter:
      name-json-path: $.sub
      first-name-json-path: $.given_name
      last-name-json-path: $.family_name
      roles-json-path: $.realm_access.roles
      roles-value-list: true
      role-prefix: "ROLE_"
      role-case-transformation: to_upper_case
      role-string-replacements:
        - regex: "[- ]"
          replacement: "_"
        - regex: "_ADMINS"
          replacement: "_ADMIN"
      role-mapping:
        - source: "Domain Admins"
          target: "ROLE_ADMIN"
        - source: "samba-admins"
          target: "ROLE_ADMIN"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: samba-ad-dc-manager-pkce
      use-pkce-with-authorization-code-grant: true
  open-api:
    # see: https://github.com/OAI/OpenAPI-Specification/blob/3.1.1/versions/3.1.1.md#info-object
    info:
      title: Group Manager API
      summary: A group manager.
      description: RESTful service for group manager application.
      # termsOfService: https://example.com/terms/
      # contact:
      #   name: API Support
      #   url: https://www.example.com/support
      #   email: support@example.com
      license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: 4.0.0-SNAPSHOT

---

spring:
  config:
    activate:
      on-profile: test

  security:
    user:
      name: testuser
      password: changeit
      roles:
        - "USER"
        - "LOCAL_USER"
        - "ADMIN"
        - "ACTUATOR_ADMIN"
